# Generated by Django 5.2.1 on 2025-06-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blogs_images/",
                        verbose_name="Превью",
                    ),
                ),
                ("views_count", models.IntegerField(verbose_name="Счетчик просмотров")),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блог",
            },
        ),
    ]
