# Generated by Django 5.2.1 on 2025-06-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "Блог", "verbose_name_plural": "Блоги"},
        ),
    ]
