# Generated by Django 5.2.1 on 2025-06-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_blog_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Счетчик просмотров"
            ),
        ),
    ]
