# Generated by Django 5.2.1 on 2025-06-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_blog_is_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="is_valid",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Признак публикации"
            ),
        ),
    ]
