# Generated by Django 5.2.1 on 2025-06-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="products/",
                null=True,
                upload_to="products/",
                verbose_name="Изображение",
            ),
        ),
    ]
